CREATE TABLE IF NOT EXISTS "Players" (
    "Id" TEXT NOT NULL,
    "OwnerId" TEXT NOT NULL,
    "Version" INT NOT NULL DEFAULT 1,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT PK_Players PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_Players_OwnerId ON "Players" USING btree ("OwnerId");