CREATE TABLE IF NOT EXISTS "Players" (
    "Id" TEXT NOT NULL,
    "OwnerId" TEXT NOT NULL,
    "Version" INT NOT NULL DEFAULT 1,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "Data" TEXT NOT NULL,
    CONSTRAINT PK_Players PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_Players_OwnerId ON "Players" USING btree ("OwnerId");

CREATE TABLE IF NOT EXISTS "MatchResults" (
    "Id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "WinnerId" TEXT NOT NULL,
    "LoserId" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT PK_Players PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_Results_WinnerId ON "MatchResults" USING btree ("WinnerId");
CREATE UNIQUE INDEX IF NOT EXISTS IDX_Results_LoserId ON "MatchResults" USING btree ("LoserId");