CREATE TABLE IF NOT EXISTS "Players" (
    "Id" TEXT NOT NULL,
    "Version" INT NOT NULL DEFAULT 1,
    "CreatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "DeviceId" TEXT NOT NULL,
    CONSTRAINT PK_Players PRIMARY KEY ("Id")
);